language: node_js
node_js:
  - 14.16.0
script: npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy $AES_PASS
  on:
    branch: master
branches:
  only:
    - master
    - development
