language: node_js
node_js:
  - 14.17.0
script: npm run test
deploy:
  provider: script
  script: bash scripts/deploy $AES_PASS
  on:
    branch: master
  skip_cleanup: true
branches:
  only:
    - master
    - development
