version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: scripts/build_server.sh
      timeout: 3000
      runas: root
    - location: scripts/start_server.sh
      timeout: 1500
      runas: root
