export { default as About } from "./About"
export { default as Home } from "./Home"
export { default as Portfolio } from "./Portfolio"
export { default as Music } from "./Music"
export { default as Books } from "./Books"
